resources:
  - statefulset.yaml
  - service.yaml
  - endpoints.yaml
  - service-account.yaml

commonLabels:
  app: postgres

vars:
  - name: CLUSTER_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: postgres
    fieldref:
      fieldpath: metadata.labels.cluster-name

configMapGenerator:
- name: postgres
  literals:
    - BACKUP_SCHEDULE='00 01 * * *'
    - DEBUG=true
    
secretGenerator:
- name: postgres
  commands:
    PATRONI_SUPERUSER_PASSWORD: "printf $SUPERUSER_PASSWORD"
    PATRONI_REPLICATION_PASSWORD: "printf $REPLICATION_PASSWORD"
  type: Opaque
    
